import Head from "next/head";
import {APP_NAME} from "@/utils/constants";
import Home from "@/components/@page-components/home";

const  HomePage = () => {
  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
    </>
  );
}

export default HomePage;
